name: Deploy Spring Boot Application

on:
  push:
    branches:
      - feature  # feature 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. JDK 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Gradle 빌드 (Maven 사용 시 변경)
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test

      # 4. 원격 서버에 JAR 파일 업로드 (SSH 방식)
      - name: Deploy to Server via SSH
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          source: "build/libs/*.jar"
          target: ${{ secrets.APP_DIRECTORY }}

      # 5. 원격 서버에서 기존 애플리케이션 중지 및 새로 실행
      - name: Restart Application
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          script: |
            cd ${{ secrets.APP_DIRECTORY }}
            pkill -f 'java -jar' || true  # 기존 애플리케이션 종료
            
            # RDS 환경 변수 설정
            export SPRING_DATASOURCE_URL="${{ secrets.SPRING_DATASOURCE_URL }}"
            export SPRING_DATASOURCE_USERNAME="${{ secrets.SPRING_DATASOURCE_USERNAME }}"
            export SPRING_DATASOURCE_PASSWORD="${{ secrets.SPRING_DATASOURCE_PASSWORD }}"
            export REDIS_HOST="${{ secrets.REDIS_HOST }}"
            export REDIS_PORT="${{ secrets.REDIS_PORT }}"
            export AWS_ACCESS_KEY="${{ secrets.AWS_ACCESS_KEY }}"
            export AWS_SECRET_KEY="${{ secrets.AWS_SECRET_KEY }}"
            export AWS_S3_REGION="${{ secrets.AWS_S3_REGION }}"
            export AWS_S3_BUCKET="${{ secrets.AWS_S3_BUCKET }}"
            export JWT_SECRET="${{ secrets.JWT_SECRET }}"
            export JWT_EXPIRY="${{ secrets.JWT_EXPIRY }}"
            export TOSS_SECRET_KEY="${{ secrets.TOSS_SECRET_KEY }}"
            export TOSS_CLIENT_KEY="${{ secrets.TOSS_CLIENT_KEY }}"
            
            # JAR 실행
            nohup java -jar $(ls -t *.jar | head -n 1) > app.log 2>&1 &
